version: '3.7'

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    networks:
      network:
        ipv4_address: 172.28.1.1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  remote_host:
    image: centos-remote-host
    container_name: centos-remote-host
    build:
      context: ./centos
    networks:
      network:
        ipv4_address: 172.28.1.2
    volumes:
      - ./centos/script.sh:/tmp/script.sh
