version: '3.7'

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  jenkins:
    build:
      context: .
    image: jenkins
    container_name: jenkins
    networks:
      network:
        ipv4_address: 172.28.1.1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  postgres:
    image: postgres:9.6
    container_name: postgres
    networks:
      network:
        ipv4_address: 172.28.1.2
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    restart: always

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      network:
        ipv4_address: 172.28.1.3
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres